README.md, lib/cloudant.js
=> Use the Cloudant Query selector syntax to associate models to

lib/cloudant.js, test/imported.test.js, test/maxrows.test.js, test/regexp.test.js
=> Fix lint error and handle error

package.json
Connect to https://github.com/strongloop-internal/scrum-loopback/issues/1041
=> Update juggler version to ^3.0.0-alpha.7

intl/ja/messages.json
https://github.com/strongloop-internal/scrum-loopback/issues/1097
=> Update translation files - round#2

test/init.js
Backport of #39 
cc @strongloop/fa-db-connectors
=> Backport: Add connectorCapabilities global object (#39)

README.md
Guide users and developers to get access to cloudant dashboard.
=> How to sign in cloudant account to see dashboard

README.md
connect to strongloop-internal/scrum-loopback#1436
update link to point to lb3 datasource generator page
=> update to lb3  datasource generator page

README.md
@0candy 
This is primarily formatting fixes so the README lays out properly in the docs, with a bit of content cleanup and editing to conform to our style guide.
=> Fix formatting in docs

test/init.js
Connect to https://github.com/strongloop/loopback/issues/517
Add nestedProperty to connectorCapabilities so loopback-datasource-juggler can read it when deciding test relative features or not.
=> Add nestedProperty to connectorCapabilities

README.md, doc/advanced-queries.md
Add documentation for Regex Filtering, which explains how Cloudant's regex filtering works, and how the connector will automatically provide the necessary additions to a query if omitted by the user.
#77
=> Add advanced queries document

lib/cloudant.js
https://github.com/strongloop/loopback-connector-cloudant/issues/73
=> Catch undefined docs

lib/cloudant.js
Fix the typo in
https://github.com/strongloop/loopback-connector-cloudant/pull/85/files#diff-fa06ecf3249c63aabcbf7ff1ae8ec186R280
=> Fix error message typo

lib/cloudant.js
This reverts commit 4a70c3be9a8756d29d857caa797dbd4923500b02.
https://github.com/strongloop/loopback-connector-cloudant/issues/78#issuecomment-284454583
=> Revert "Build selector with array type data"

README.md
Add docs for users to be aware of cloudant's behaviour on "update" of a document.
=> Add advisory note regarding update

doc/advanced-queries.md
Connect to https://github.com/strongloop/loopback-connector-cloudant/pull/90
Add more docs to explain filter and order in cloudant.
=> Add doc for filter and order

package.json
Update `loopback-connector` to use v4
=> Update connector to 4.0.0

lib/cloudant.js, test/automigrate.test.js, test/cloudant.test.js, test/regexp.test.js
A commit cherry-picked from https://github.com/strongloop/loopback-connector-cloudant/pull/91
PR#91 passes successfully on local but has random CI failure, I break down the big PR to investigate which commit introduces the failure.
Turns out CI is good with this commit, so I am going to merge it first then back to PR#91.
=> Fix regexp.test.js

test/maxrows.test.js
connect to strongloop/loopback-connector-cloudant#33
write request still runs into limit problem.
=> Recover maxrows.test.js

test/init.js
Fix CI for 1.x branch
connect to: https://github.com/strongloop/loopback-datasource-juggler/pull/1342
=> [1.x] Fix CI for 1.x branch

test/init.js
Fix CI for 2.x, in order to get juggler 2.x CI to pass
connect to: strongloop/loopback-datasource-juggler#1342
=> [loopback-2.x] Fix CI

README.md, lib/cloudant.js, package.json, test/automigrate.test.js, test/cloudant.test.js, test/connection.test.js, test/maxrows.test.js, test/regexp.test.js
call our cloudant driver inside connect function when connector initializes and strip the path of the url and use it as the database name before passing it to our driver because of https://github.com/cloudant/nodejs-cloudant/issues/181.
connected to https://github.com/strongloop-internal/scrum-apex/issues/38
=> call driver inside connect

lib/cloudant.js, test/cloudant.test.js
connect to https://github.com/strongloop/loopback-connector-cloudant/issues/31
- None
=> Allow id property to be a number

lib/cloudant.js
2nd round of refactoring to cloudant.js
=> Refactor functions in cloudant.js

lib/cloudant.js, package.json, test/cloudant.test.js
Connected to https://github.com/strongloop-internal/scrum-apex/issues/62
#47 
#44 
=> overwrite array prop value on update

.travis.yml, docker-compose.yml, setup.sh
connected to strongloop-internal/scrum-apex#203
Use Cloudant Local in Docker container with Travis CI.
=> Setup Travis with Docker Compose

lib/cloudant.js
Refactor the big chunk of code in `Cloudant.prototype.all` function.
=> Refactor on Cloudant.prototype.all

lib/cloudant.js
Refactor the big chunk of code in `Cloudant.prototype.buildSort` function.
=> Refactor buildSort function

lib/cloudant.js
Refactor the big chunk of code in `Cloudant.prototype.buildSelector` function.
=> Refactor Cloudant.prototype.buildSelector function

test/cloudant.test.js, test/maxrows.test.js
The current tests aren't properly cleaning up after themselves, this PR should solve the problem.
Connect to https://github.com/strongloop-internal/scrum-apex/issues/204
=> cloudant.test: cleanup after test runs

intl/en/messages.json, lib/cloudant.js
connect to https://github.com/strongloop-internal/scrum-apex/issues/204
=> Refactor functions in cloudant

README.md, test/cloudant.test.js
connect to strongloop/loopback-connector-cloudant#88
=> Add proxy config test

README.md, docker-compose.yml, setup.sh
- Fix typo on docker docs
- Enable a separate check for docker-compose
- Fix indentation on docker-compose.yml
=> Fix typo on docker docs

.travis.yml, package.json, test.js
Backport for https://github.com/strongloop/loopback-connector-cloudant/pull/139
=> Backport docker ci

lib/cloudant.js, test/update.test.js
Backport for #145 
connect to https://github.com/strongloop/loopback-connector-cloudant/issues/37
=> Backport: return back result count in updateAll

test/create.test.js, test/find.test.js, test/lib/test-util.js, test/replace.test.js, test/update.test.js
Callback error message in tests.
=> Check error and result

README.md, lib/cloudant.js, test/update.test.js
Implement a cloudant specific bulk update function. Call it `massUpdate`. The function takes in an array of data and performs bulk update against the model instance where the `_rev` of the datas match.
connect to https://github.com/strongloop/loopback-connector-cloudant/issues/35
=> Add cloudant specific bulkReplace function

package.json, test.js
connect to https://github.com/strongloop-internal/scrum-apex/issues/257
=> Require init on mocha args

lib/cloudant.js, test/init.js
Fixes the failing upsertWithWhere & prototype.delete Test Cases
=> Fixes failing tests on manipulation.test.js

lib/cloudant.js, test/id.test.js
Fixes an issue where if _id was set as id on model, any query won’t
return _id anymore.
=> Fix to return _id to when it is model id

README.md
If there are two models using `_id` as pk, and with `forceId: false`, there is a possibility of a document conflict.
For example:
```
{_id: 'myid', loopback__model__name: 'Foo'}
{_id: 'myid', loopback__model__name: 'Bar'}
```
This PR adds advisory docs on the behaviour of using `forceId` and leaves the onus on the user to use the flag.
fixes https://github.com/strongloop-internal/scrum-apex/issues/255
=> Add advisory docs on forceId

intl/en/messages.json
=> add globalize string

package.json
Updating debug required version from 2.2.0 to 2.6.9.
> eslint .
(+) 1 vulnerabilities found
┌───────────────┬─────────────────────────────────────────────────────────────────┐
│               │ Regular Expression Denial of Service                            │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Name          │ debug                                                           │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ CVSS          │ 3.7 (Low)                                                       │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Installed     │ 2.2.0                                                           │ …
=> Update package.json to remove security vulnerability

package.json, test/imported.test.js
related to https://github.com/strongloop/loopback-connector-couchdb2/issues/41
A follow up PR of https://github.com/strongloop/loopback-connector-couchdb2/pull/42, import new test file in cloudant:
=> Add count test

.travis.yml, package.json
Drop Node 4, and add Node 8 and 10 in Travis.
=> chore: update node versions in travis

lib/cloudant.js, lib/geo.js, test/geo.test.js
Added a mixin for Cloudant Geospatial queries.
- connect to strongloop/loopback#190
=> Cloudant Geospatial

README.md
Updated the README with documentation for the new Geospatial API.
- N/A
=> Geospatial README

example/example.js, index.js, lib/cloudant.js, lib/geo.js, lib/view.js, package.json, test.js, test/cloudant.connection.test.js, test/cloudant.test.js, test/geo.test.js, test/imported.test.js, test/init.js, test/lib/test-util.js
- add `"author": "IBM Corp.",` in package.json so that `slt copyright` command can generate the right header
- Update copyrights year
=> chore: update copyrights years

.travis.yml
Add node 12 to travis CI.
- connect to https://github.com/strongloop/loopback-next/issues/3111
- replaces https://github.com/strongloop/loopback-connector-cloudant/pull/210
=> chore: add node 12 to travis ci

package.json
=> fixup!: fix the dependency version

test.js
See https://github.com/strongloop/loopback-next/pull/4484.
=> replace couchDB3 docker image with a stable version

docker.setup.js, lib/migrate.js, test.js, test/partition.test.js
connects to https://github.com/strongloop-internal/scrum-apex/issues/440
=> chore: update copyright year

.vscode/settings.json, README.md
=> docs: iam auth

package.json
Related to https://github.com/strongloop/loopback-next/issues/4585.
Update `strong-globalize` to 6.x.
=> chore: update strong-globalize to 6.x

README.md
Fixing the dup TOC and the parsing:
=> update: docs

.github/ISSUE_TEMPLATE/Question.md, .travis.yml, README.md, doc/multiple-db-instances.md, doc/partitioned-db.md, package.json
Signed-off-by: Diana Lau <dhmlau@ca.ibm.com>
As part of strongloop/loopback-next#7595
=> chore: move repo to loopbackio org
