lib/cloudant.js

Connect to strongloop/loopback#2242
When booting app from swagger generator, datasources are setup with ds.lazyConnect = true to avoid connection.

Lazy connect when booting from swagger generator

---

.gitignore
example/example.js
index.js
intl/en/messages.json
lib/cloudant.js
package.json

Add globalization

---

lib/cloudant.js
test/regexp.test.js

This is a fix for #25.
`Cloudant.prototype.buildSelector` now parses the `ignoreCase` from RegExp objects and provides it to the `$regex` operator in PCRE format by prepending `(?i)` to the expression.

Added check for ignoreCase flag on RegExp queries.

---

lib/cloudant.js
test/cloudant.test.js
test/describe.js
test/imported.test.js
test/maxrows.test.js
test/regexp.test.js

Connect to strongloop-internal/scrum-loopback#991
- Almost copy from `updateOrCreate`, which is actually doing replace not update.
- At the end of the function, return data got from db.
- Add an option `upsert` in function `create`, check id exist if `upsert === false`, default value is undefined.
- `replaceById` will eventually call `replaceOrCreate` with option `upsert === false`

Add replaceOrCreate 

---

README.md

Connect to https://github.com/strongloop-internal/scrum-loopback/issues/1053
I just discovered another way to create cloudant instance(DBaaS),  easier than the bluemix one. Explained it in README.md file.
Confirmed that DBaaS account works:
```
jannyHous-MacBook-Pro:loopback-connector-cloudant jannyhou$ CLOUDANT_USERNAME=jannyhou CLOUDANT_PASSWORD=cannot_tell_you CLOUDANT_DATABASE=test npm test
> loopback-connector-cloudant@1.1.0 test /Users/jannyhou/lb/lb-project/loopback-connector-cloudant
> mocha -G --timeout 10000
cloudant connector
replaceOrCreate
✓ should replace a model instance if the passing key already exists (591ms)
replaceById
✓ should replace the model instance if the provided key already exists (578ms)
```

How to setup cloudant and run testing

---

README.md

Connect to strongloop/loopback-connector-cloudant#18
Add explanation to warn users an invalid url string will result in uncaught error and fail their app.
PTAL @strongloop/squad-apex . Thanks.

Explain uncaught url error in doc

---

lib/cloudant.js
test/cloudant.test.js

Arbitrary properties of the settings object will now be passed
to the driver to allow configuration of nodejs-cloudant settings.
#56

cloudant: allow passthrough of settings

---

lib/cloudant.js
test/cloudant.test.js

invoking updateAll() with input data in loopback
model instance format was causing failures as
it was not converted to canonical presentation.
This fix resolves it by checking if input data
is a model instance and if it is, convert it to
a plain JSON object for update.
Fixes #71
- None

Fix updateAll for model instance as input

---

lib/cloudant.js

Connect to strongloop/loopback-connector-cloudant#75
Append field type for nested properties. Before the pr it only applies to first level property.
Test case is in juggler https://github.com/strongloop/loopback-datasource-juggler/pull/1239/files#diff-8fae24fa21c82e23f7f43ccdae4fcf90R635

Append field type for nested properties

---

lib/cloudant.js

Connect to https://github.com/strongloop/loopback-connector-cloudant/issues/77
`$regex` cannot be a basis of query, have to make basis a equality operator to get `$regex` applied.
In this pr, whenever a query with `$regex` is built and there is no condition on `_id`, add `{ "_id": { "$gt": null }}` to the query
---
Test case in juggler: https://github.com/strongloop/loopback-datasource-juggler/pull/1239

Make equality operator as query basis when query contains regex

---

lib/cloudant.js

connect to strongloop/loopback-connector-cloudant#78
When filter against array data, e.g. `friends.name` in the example below is `Array`, the current query is:
`{where: {friends.name: 'Ringo Starr'}}`
while the *right query* is: 
`{where: {friends: {$elemMatch: {name: 'Ringo Starr'}}}}`
This PR wraps array filter with `$elemMatch`.
---
Test case is in juggler: https://github.com/strongloop/loopback-datasource-juggler/pull/1239/files#diff-8fae24fa21c82e23f7f43ccdae4fcf90R646

Build selector with array type data

---

lib/cloudant.js
package.json
test/cloudant.test.js
test/init.js

Parent issue: strongloop/loopback#517
Sub-issue in cloudant:
- support array type: https://github.com/strongloop/loopback-connector-cloudant/issues/78
- append sorting data type: https://github.com/strongloop/loopback-connector-cloudant/issues/75
pr for issue#78 is reverted because the algorithm need redesign.
This pr includes implementation of issue#78 and fix for issue#75 
Related test cases in juggler: https://github.com/strongloop/loopback-datasource-juggler/blob/master/test/basic-querying.test.js#L602
Support array type: 
- given a nested field like `field1.field2.field3.field4`, cloudant searches datatype for each field, and insert a `$elemMatch` after if it's an array. e.g. if field2 is an array, the new field will be `field1.field2.$elemMatch.field3.field4`.
- cloudant db only …

Support nested property filter

---

README.md

Update readme to have example for
datasource config using url field.
Also, specify limitations for our
cloudant driver.
#18 

add url config example

---

lib/cloudant.js
test/automigrate.test.js
test/cloudant.test.js

strongloop/loopback-connector-cloudant#92
cloudant has its own `define` function that overrides the one in loopback-connector. It doesn't only add a model to datasource's `_model` object, but also **update** the index, which is exactly what `automigrate` does.
I remove `define` function in this PR because in loopback-datasource-juggler and other loopback components like loopback-boot, `define` is used as a sync function, while update index in cloudant is an async function. https://github.com/strongloop/loopback-connector-cloudant/issues/92 and https://github.com/strongloop/loopback-connector-cloudant/issues/93 are caused by this.
This will be a breaking change since user will have to call `db.automigrate` to migrate their models to database, cloudant won't automatically update the index …

Use define function in loopback-connector

---

lib/cloudant.js
test/cloudant.test.js
test/maxrows.test.js

connect to strongloop/loopback-connector-cloudant#33
The sort query builder doesn't check first level property exist when it searches for its type.

Fix sort query builder

---

lib/cloudant.js
test/cloudant.test.js

Backport for https://github.com/strongloop/loopback-connector-cloudant/pull/69
Arbitrary properties of the settings object will now be passed
to the driver to allow configuration of nodejs-cloudant settings.
connect to https://github.com/strongloop/loopback-connector-cloudant/issues/113

backport allow passthrough of settings to 1.x

---

lib/cloudant.js
test/automigrate.test.js
test/cloudant.test.js
test/init.js
test/maxrows.test.js
test/regexp.test.js

Expected behaviour:
`autoupdate`: updateIndex for models attached to db.
~`automigrate`: do autoupdate, then destroy model instances if model existing.~
`automigrate`: destroy model instances if model existing, then do destroy.
Current behaviour:
`autoupdate` and `automigrate` does same thing: just updateIndex
connect to strongloop/loopback-connector-cloudant#33
- None

autoupdate and automigrate fix

---

lib/cloudant.js
test/cloudant.test.js

related to https://github.com/strongloop/loopback-connector-cloudant/pull/111

1.x fix/upsert

---

lib/cloudant.js
test/cloudant.test.js

Allow use of `updateAttributes` on the `updateOrCreate` prototype function. Try updating the data using the `updateAttributes` function first and if it fails, create the instance.
connect to https://github.com/strongloop-internal/scrum-apex/issues/204

Fix updateOrCreate

---

README.md
package.json
setup.sh

connect to https://github.com/strongloop-internal/scrum-apex/issues/216

Add docker setup

---

.travis.yml

Allow travis to run against the latest code base instead of npmjs.

Allow travis to run against the latest code base

---

README.md
docker-compose.yml
package.json
setup.sh

Dockerode script is good for CI, but it cleans up after the test
The script keeps the docker container alive and allows to debug easily on test failures

Allow users to spawn docker and run tests

---

doc/advanced-queries.md

User complains '$regex' operator is not recognized. The reason is in loopback syntax it should be `regexp`, the connector converts it to a cloudant syntax `$regex` then send the query to database.  
connect to strongloop/loopback-connector-cloudant#20

Add regexp doc

---

lib/cloudant.js
test/update.test.js

Currently, cloudant returns an array of the updated instances instead of the count of the instances updated. This behaviour is not consistent with other connectors. The fix returns the number of instances updated instead of the instances itself.
connect to https://github.com/strongloop/loopback-connector-cloudant/issues/37

Make updateAll return count of updated instances

---

lib/cloudant.js
test/cloudant.test.js
test/update.test.js

~Currently in cloudant `update` performs a destructive update. With this change `update` function should do partial update.~
~- Use `updateAttributes` function to `update` a model instance.~
~- Use `update` function in `updateOrCreate` to update a model instance if exists.~
- Fix `updateAttributes` function to return the docs from `fromDB` function correctly. This is required since `updateOrCreate` calls `updateAttributes` now.
- Remove duplicate `updateAll` tests
- Allow `fromDB` function to return the id as a number if the original property was a number
connect to https://github.com/strongloop/loopback-connector-cloudant/issues/35

Fix updateAttributes method

---

README.md
lib/cloudant.js
test/cloudant.test.js
test/update.test.js

Return the result in `updateAll` in a correct manner.  Check for error on update if any exists.
connect to #35

Fix update/updateAll functions

---

README.md

Advisory note on `bulkReplace` function not triggering any operation hooks under the hood.

Fix docs on bulk replace operation hooks

---

README.md
lib/cloudant.js
test/create.test.js

Currently, we as the ORM strips off the `_rev` value before doing a create operation. This is not needed since, cloudant ignores the `_rev` value when passed into the payload data for its own clarity. So if the user specifies the `_rev` value, **it is upto them to know that value won't be accepted as cloudant will automatically generate a unique _rev value**
connect to https://github.com/strongloop-internal/scrum-apex/issues/234

Do not strip rev value on create

---

lib/cloudant.js
package.json
test/imported.test.js
test/init.js

connect to  strongloop/loopback-connector-cloudant#33
related to https://github.com/strongloop/loopback-datasource-juggler/pull/1420

Recover manipulation.test.js

---

package.json

I simply updated the cloudant dependency because there is something wrong with this version of cloudant in the npm registry. 
I went ahead and added a PR for this because we are using this package in some of our apps that run on bluemix and our deployment pipelines are failing because this package will not build and I figured there may be other people having the same issue. :) 
Just FYI for any one stumbling across this, we have temporarily fixed this deployment issue by pointing our npm packages to this fork. But we are hoping to point it back to the main repo as soon as we can. 
- connect to #185 

Updated cloudant dependency

---

README.md

The old link redirect to a new docs but not the correct subpage

fix external link to Selector syntax

---

lib/cloudant.js
test/id.test.js
test/settings.globalLimit.test.js

A workaround to fix https://github.com/strongloop/loopback/issues/4006
Details see https://github.com/strongloop/loopback/issues/4006#issuecomment-423558014
This fix at least allow people to retrieve all related model instances by setting a global limit.
*PS: Travis is unstable, but I don't have the time to investigate why, sorry. jenkins pass*

Global limit/all

---

test/init.js

Fix the new test failure observed in https://github.com/strongloop/loopback-datasource-juggler/pull/1705.
- connect to strongloop/loopback-datasource-juggler#1692
- see also #201

Fix test setup of autoupgrade/autoupdate

---

package.json

Update `strong-globalize` version to use the latest 4.x version, and other dependencies.
Related to https://github.com/strongloop-internal/scrum-apex/issues/372

chore: update strong-globalize

---

.travis.yml
package.json

As we are changing to execute tests from both juggler versions 3.x and 4.x, and juggler v4 does not support Node.js 6, update node configs to skip tests for Node.js 6.
- connect to https://github.com/strongloop/loopback-connector-cloudant/pull/206

update node version to skip imported test for older version

---

example/example.js
index.js
lib/cloudant.js
lib/geo.js
lib/view.js
package.json
test.js
test/cloudant.connection.test.js
test/cloudant.test.js
test/geo.test.js
test/imported.test.js
test/init.js
test/lib/test-util.js

As we are changing to execute tests from both juggler versions 3.x and 4.x, update `eslint` to newer version to pass CI tests.
The version of `eslint` matches with ~[mongoDB connector](https://github.com/strongloop/loopback-connector-mongodb/commit/830f83a9eb59190975436b9d7bf353fe743b219b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R40)~ latest version
- connect to https://github.com/strongloop/loopback-connector-cloudant/pull/206

Update eslint version

---

lib/cloudant.js
lib/migrate.js
package.json
test.js
test/partition.test.js

connect to https://github.com/strongloop/loopback-connector-cloudant/issues/216
Support create partitioned index in partitioned database.
User can define the index in model config as 
```js
Product = db.define('Product', {
prodName: {type: String},
desc: {type: String},
}, {
indexes: {
'prodName_index': {
// Partitioned index
partitioned: true,
keys: {
prodName: 1,
},
},
},
});
```
to create partitioned index.
If no `partitioned` property defined, the default index will be global. 
~TODO:~
- connect to <link_to_referenced_issue>

feat: partitioned index

---

lib/cloudant.js
package.json
test/partition.test.js

Prerequisite PR: https://github.com/strongloop/loopback-connector-couchdb2/pull/71
connect to https://github.com/strongloop/loopback-connector-cloudant/issues/220
To trigger the `partitonedFind`, you can include the `partitionKey` field in `options` like:
```
Product.find(
{where: {tag: 'food'}},
// specify the partition key in the options
{partitionKey: 'toronto'},
cb
)
```
- connect to https://github.com/strongloop/loopback-connector-cloudant/issues/220

Partition key from option

---

.npmignore
package.json

Related to: https://github.com/strongloop/loopback-connector-mssql/issues/222 
Using similar fix applied to loopback-connector-mssql : https://github.com/strongloop/loopback-connector-mssql/pull/226 

Exclude 'deps' and '.github' from npm publish

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

Switch from CLA to DCO as the contribution method. 
Related to: https://github.com/strongloop-internal/scrum-apex/issues/449

chore: Switch DCO as contribution method
